url: https://www.yaneq.com/
baseurl:

# Site settings
title: yaneq.com
email: hello@yaneq.com
description: "Mobile app development agency based in Barcelona. We are specialized in React Native, JavaScript, iOS, Android, Cross-Platform, Continuous Integration, Delivery, Deployment, Automated Testing"


# Team names, titles and social links
people:
- name: Jan Koeppen
  pic: 1
  position: Founder
  social:
    - title: twitter
      url: https://github.com/yaneq
    - title: linkedin
      url: https://www.linkedin.com/in/jkoeppen/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://github.com/yaneq
  - title: github
    url: http://github.com/yaneq

# Postal address (add as many lines as necessary)
address:
  - line: Navas de Tolosa, 300
  - line: 08027 Barcelona

# Build settings
markdown: kramdown
permalink: pretty
